name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: print content
        run: |
          mkdir .ssh && chmod 700 .ssh && cd .ssh
          touch devops.pem && chmod 600 devops.pem
          echo "${{ secrets.key }}" /p=1 >> devops.pem
          cat devops.pem

