name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      - name: Code checkout
#        uses: actions/checkout@v2.5.0
#        with:
#          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: print content
        run: |
          mkdir .ssh
          ls
          chmod 700 .ssh
          cd .ssh
          ls
          touch devops.pem
          chmod 600 devops.pem
          echo "${{ secrets.AWS_KEY }}" /p=1 >> devops.pem
          ls
          ssh -i "devops.pem" ec2-user@ec2-35-173-211-195.compute-1.amazonaws.com

