name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run ansible playbook
        run: |
          echo "$PWD"
          ansible-playbook ansible/ec2_deploy.yml

