name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run ansible playbook
        uses: tomasnorre/ansible-cli-action@0.0.5
        with:
          command: "ansible-playbook main.yml"

