name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run ansible playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: 'built_and_test_eshop.yml'

