name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
#      - name: Code checkout
#        uses: actions/checkout@v2.5.0
#        with:
#          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: create pem key
        run: |
          mkdir .ssh
          chmod 700 .ssh
          cd .ssh
          touch devops.pem
          chmod 600 devops.pem
          echo "${{ secrets.AWS_KEY }}" /p=1 >> devops.pem

      - name: check key
        run: |
          ls -la

      - name: connect via ssh
        uses: D3rHase/ssh-command-action@{version}
        with:
          host: ${{secrets.EC2_HOST}}
          user: ${{secrets.EC2_USERNAME}}
          private_key: devops.pem
          command: touch neco.txt

