name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run ansible playbook
        run: |
          ssh ec2-user@ec2-52-90-85-163.compute-1.amazonaws.com

