name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run ansible playbook
        run: |
          echo "$PWD"
          ls
          cat ansible/ec2_deploy.yml
          ansible-playbook ./ansible/ec2_deploy.yml

