name: run ansible
on:
  workflow_dispatch:
  push:

jobs:

  Deploy:
    name: Deploy eshop to AWS EC2 machine
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:

      - name: run via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{ secrets.AWS_KEY }}
          script: |
            git clone https://github.com/OG-Gardavsky/4IT572_DevOps-basics.git
            cd 4IT572_DevOps-basics
            echo "${{ secrets.AWS_KEY }}" > devops.pem
            chmod 600 devops.pem
            ANSIBLE_HOST_KEY_CHECKING=False ~/.local/bin/ansible-playbook ansible/ec2_deploy.yml --extra-vars "access_key=${{secrets.AWS_ACCESS_KEY_ID}} secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}} session_token=${{secrets.AWS_SESSION_TOKEN}}" --user ec2-user --key-file devops.pem





