name: run ansible
on:
  workflow_dispatch:
  push:


jobs:

  Deploy:
    name: Deploy eshop to AWS EC2 machine
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:

      - name: install pip
        run: |
          ansible-galaxy collection install amazon.aws
          pip3 install ansible boto boto3 botocore

      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: ec2_deploy.yml
          directory: ansible
          key: ${{secrets.AWS_KEY}}
          options: |
            --extra-vars "access_key=${{secrets.AWS_ACCESS_KEY_ID}} secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}} session_token=${{secrets.AWS_SESSION_TOKEN}}"



#      - name: create pem key
#        run: |
#          mkdir .ssh
#          chmod 700 .ssh
#          cd .ssh
#          touch devops.pem
#          chmod 600 devops.pem
#          echo "${{ secrets.AWS_KEY }}" /p=1 >> devops.pem
