name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: connect via ssh
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.EC2_HOST}}
          user: ${{secrets.EC2_USERNAME}}
          private_key: ${{ secrets.AWS_KEY }}
          command: |
            echo "jsem tady a nebojim se toho" >> neco.txt
            echo "jsem tady a nebojim se toho" >> neco2.txt
