name: run ansible
on:
  workflow_dispatch:


jobs:

  connect:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: connect via ssh
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.EC2_HOST}}
          user: ${{secrets.EC2_USERNAME}}
          private_key: ${{ secrets.AWS_KEY }}
          command: |
            cd 4IT572-ansible/ansible/
            ansible-playbook ec2_deploy.yml --extra-vars "access_key=${{secrets.AWS_ACCESS_KEY_ID}} access_key=${{secrets.AWS_SECRET_ACCESS_KEY}} access_key=${{secrets.AWS_SESSION_TOKEN}}" --user ec2-user --key-file ../devops.pem
